spring.application.name=ai-workspace-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/Lovable
spring.datasource.username=postgres
spring.datasource.password=Rishit@5211
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secretKey="sbdhbhbdb243r47recbbcdrennerg7843yr7e2ygeve"

logging.level.org.springframework.security=DEBUG
stripe.secret.key=${STRIPE_SECRET_KEY}